application: iphone6-hkgolden
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
#- url: /favicon\.ico
#  static_files: favicon.ico
#  upload: favicon\.ico

- url: /crawl
  script: main.crawlApp

- url: /getEmail
  script: main.getEmailApp

- url: /fix
  script: main.quickFixApp

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
